const data = () => {
  return [
    {
      ativo: "ativo1",
      velocidade: 45,
      trajeto: 159,
      aderencia: 80,
      temperatura: -5,
      umidade: 12,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 1,
        nome: "Gabriel Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 1,
          ordem: 1,
          cliente: "Coca Cola",
        },
      ],
    },
    {
      ativo: "ativo2",
      velocidade: 40,
      trajeto: 109,
      aderencia: 86,
      temperatura: -4,
      umidade: 11,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 98,
        nome: "Matheus Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo3",
      velocidade: 47,
      trajeto: 179,
      aderencia: 76,
      temperatura: -7,
      umidade: 0,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 155,
        nome: "Pedro Silva Santos",
      },
      dispositivo: {
        bateria: 5,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo4",
      velocidade: 150,
      trajeto: 189,
      aderencia: 76,
      temperatura: -7,
      umidade: 15,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 1,
        nome: "Venicyus Silva Santos",
      },
      dispositivo: {
        bateria: 55,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo1",
      velocidade: 45,
      trajeto: 159,
      aderencia: 80,
      temperatura: -5,
      umidade: 12,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 1,
        nome: "Gabriel Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 1,
          ordem: 1,
          cliente: "Coca Cola",
        },
      ],
    },
    {
      ativo: "ativo2",
      velocidade: 40,
      trajeto: 109,
      aderencia: 86,
      temperatura: -4,
      umidade: 11,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 98,
        nome: "Matheus Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo3",
      velocidade: 47,
      trajeto: 179,
      aderencia: 76,
      temperatura: -7,
      umidade: 0,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 155,
        nome: "Pedro Silva Santos",
      },
      dispositivo: {
        bateria: 5,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo4",
      velocidade: 150,
      trajeto: 189,
      aderencia: 76,
      temperatura: -7,
      umidade: 15,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 1,
        nome: "Venicyus Silva Santos",
      },
      dispositivo: {
        bateria: 55,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo1",
      velocidade: 45,
      trajeto: 159,
      aderencia: 80,
      temperatura: -5,
      umidade: 12,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 1,
        nome: "Gabriel Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 1,
          ordem: 1,
          cliente: "Coca Cola",
        },
      ],
    },
    {
      ativo: "ativo2",
      velocidade: 40,
      trajeto: 109,
      aderencia: 86,
      temperatura: -4,
      umidade: 11,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 98,
        nome: "Matheus Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo3",
      velocidade: 47,
      trajeto: 179,
      aderencia: 76,
      temperatura: -7,
      umidade: 0,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 155,
        nome: "Pedro Silva Santos",
      },
      dispositivo: {
        bateria: 5,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo4",
      velocidade: 150,
      trajeto: 189,
      aderencia: 76,
      temperatura: -7,
      umidade: 15,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 1,
        nome: "Venicyus Silva Santos",
      },
      dispositivo: {
        bateria: 55,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo1",
      velocidade: 45,
      trajeto: 159,
      aderencia: 80,
      temperatura: -5,
      umidade: 12,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 1,
        nome: "Gabriel Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 1,
          ordem: 1,
          cliente: "Coca Cola",
        },
      ],
    },
    {
      ativo: "ativo2",
      velocidade: 40,
      trajeto: 109,
      aderencia: 86,
      temperatura: -4,
      umidade: 11,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 98,
        nome: "Matheus Silva Santos",
      },
      dispositivo: {
        bateria: 14,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
    {
      ativo: "ativo3",
      velocidade: 47,
      trajeto: 179,
      aderencia: 76,
      temperatura: -7,
      umidade: 0,
      parametros: {
        temperaturaMaxima: -10,
        temperaturaMinima: 0,
        umidadeMaxima: 15,
        umidadeMinima: 0,
        velocidadeMaxima: 90,
        velocidadeMinima: 0,
        volumeMaximo: 1000,
        volumeMinimo: 200,
        pesoMaximo: 1000,
        pesoMinimo: 100,
        valorMaximo: 80000,
        valorMinimo: 10000,
      },
      motorista: {
        codigo: 155,
        nome: "Pedro Silva Santos",
      },
      dispositivo: {
        bateria: 5,
      },
      entregas: [
        {
          status: 2,
          ordem: 1,
          cliente: "Coca Cola",
        },
        {
          status: 2,
          ordem: 2,
          cliente: "Chetos",
        },
        {
          status: 3,
          ordem: 3,
          cliente: "Kabum",
        },
        {
          status: 1,
          ordem: 4,
          cliente: "Lojinha",
        },
      ],
    },
  ];
};

export default data;
